### ISSUE TITLE
Library only works with stdClass not with associative arrays

### ISSUE THREAD

**Issue by Tobion** [swaggest/json-diff#17]
We we're looking into replacing our use of https://github.com/mikemccabe/json-patch-php with this library because it seemed to be better maintained. But we found a blocking problem.

It appears this library only works correctly with stdClass representations of decoded json data but not with associative arrays which is what you get when you do `json_decode($json, true)`. It seems very counter-intuitive because it's often easier to work with arrays than with stdClass.

To illustrate the problem I modified the decoding in the example from the readme and it starts failing.

```php
$diff = new JsonDiff(json_decode($originalJson, true), json_decode($newJson, true));
$this->assertEquals(json_decode($patchJson, true), $diff->getPatch()->jsonSerialize()); 
// this does not succeed because it returns the json diff with stdClass instead of array 
// which would work for jsonSerialize as well theoretically, see https://github.com/swaggest/json-diff/blob/master/src/JsonPatch.php#L108

$original = json_decode($originalJson, true);
$patch = JsonPatch::import(json_decode($patchJson, true)); 
// import seems to work also with array, see https://github.com/swaggest/json-diff/blob/dadb65fbc6888c9066c9eb167a98a721eb0f63a1/src/JsonPatch.php#L54
$patch->apply($original); 
// apply fails because the it tries to access fields as properties on $original as stdClass
// instead of as elements of an array
```

**Comment by vearutop** [comment]
Unfortunately using associative arrays for JSON data (including JSON patches) is not the greatest idea. Limitation against associative arrays is here intentionally.

The problem is that associative array does not provide enough precision to represent JSON objects and arrays:
* `[]` and `{}` have identical associative array value, 
* `[0,1,2]` and `{"0":0,"1":1,"2":2}` have identical associative array value.

Though it is possible to come up with some workarounds to allow associative array to mimic JSON objects, I don't feel that would be right thing to do. Misusing types will lead to unnecessary ambiguity with hardly justified benefits.

To resolve JSON type on encoding PHP itself loops through array keys to check if they form a sequence: https://github.com/php/php-src/blob/master/ext/json/json_encoder.c#L39.

In case you really feel the need to represent JSON objects with associative arrays I can only suggest to leverage PHP resolver by `json_decode(json_encode($assocArray))` before feeding the value to `JsonDiff`. That may impact performance.

Sorry for not being helpful.

**Comment by Tobion** [comment]
Thanks for the answer. I'm aware of the abiguities. But most often libraries actually prefer and use associative array likes like Elastica and Doctrine JSON column type. So the only solution would be to re-encode and decode as you pointed out which is pretty bad.
What is also question is the inconsistent support of associative arrays. It works for `JsonDiff` and `JsonPatch::import` but not for `apply`. So it's possible to create a patch with your lib that cannot be applied back. To me, either associative array should not be supported and raise an explicit error or the goal should be to support everywhere (even if it could potentially be abiquious).

**Comment by j13k** [comment]
I have encountered this same issue working with documents from CouchDB. The PHP libraries that support posting and retrieving JSON documents tend to return the payloads as associative arrays. I guess the decode/encode workaround here will have to do for now...

**Comment by vearutop** [comment]
@Tobion @j13k please check [v3.6.0](https://github.com/swaggest/json-diff/releases/tag/v3.6.0), it now provides support for associative arrays.
